language: objective-c
osx_image: xcode9.2
sudo: false
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod repo update master
- pod install
script:
# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
- set -euxo pipefail
- pod lib lint --use-libraries --allow-warnings
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
